import { state } from '../../state';
import { calculateThresholdFromPercent, STOPPING_PRESETS } from '../../../lib/ml/stopping-rules';
import { createStoppingRule } from '../../../lib/ml/types';
import { showModal, hideModal } from './dialogs';
import { mlClient } from '../../../lib/ml/worker-client';
import { renderMlStats } from './render';

export function showStoppingSettingsDialog() {
    const totalRecords = state.references.length;
    let currentThreshold = state.mlState.stoppingRule?.threshold || 50;

    const body = document.createElement('div');
    body.innerHTML = `
        <div class="stopping-options-tabs">
            <button id="tab-custom" class="stopping-tab-btn active">カスタム</button>
            <button id="tab-percent" class="stopping-tab-btn">割合 (%)</button>
        </div>
        
        <div id="panel-custom">
            <label>連続 Exclude 件数:</label>
            <input type="number" id="threshold-input" value="${currentThreshold}" min="1" max="${totalRecords}" style="width: 100%; padding: 8px; margin-top: 4px;">
            <p style="font-size: 12px; color: #666; margin-top: 4px;">
                指定した件数だけ連続で Exclude されたら停止を推奨します。
            </p>
        </div>

        <div id="panel-percent" class="hidden">
            <label>データセット全体の割合:</label>
            <div class="preset-chip-container" id="preset-container">
                <!-- presets generated by JS -->
            </div>
            <p style="font-size: 12px; color: #666;">
                選択した割合: <span id="calculated-count">-</span> 件
            </p>
        </div>
    `;

    // Presets generation
    const presetContainer = body.querySelector('#preset-container')!;
    STOPPING_PRESETS.forEach(preset => {
        const chip = document.createElement('div');
        chip.className = 'preset-chip';
        chip.textContent = `${preset.label}`;
        chip.onclick = () => {
            // Calculate count
            const count = calculateThresholdFromPercent(totalRecords, preset.percent);
            currentThreshold = count;
            updateDisplay();

            // Update active state
            presetContainer.querySelectorAll('.preset-chip').forEach(c => c.classList.remove('selected'));
            chip.classList.add('selected');
        };
        presetContainer.appendChild(chip);
    });

    // Tab switching
    const tabCustom = body.querySelector('#tab-custom') as HTMLElement;
    const tabPercent = body.querySelector('#tab-percent') as HTMLElement;
    const panelCustom = body.querySelector('#panel-custom') as HTMLElement;
    const panelPercent = body.querySelector('#panel-percent') as HTMLElement;

    tabCustom.onclick = () => {
        tabCustom.classList.add('active');
        tabPercent.classList.remove('active');
        panelCustom.classList.remove('hidden');
        panelPercent.classList.add('hidden');
    };

    tabPercent.onclick = () => {
        tabPercent.classList.add('active');
        tabCustom.classList.remove('active');
        panelPercent.classList.remove('hidden');
        panelCustom.classList.add('hidden');
        updateDisplay();
    };

    // Update display helper
    const updateDisplay = () => {
        const input = body.querySelector('#threshold-input') as HTMLInputElement;
        const calcDisplay = body.querySelector('#calculated-count') as HTMLElement;

        input.value = currentThreshold.toString();
        calcDisplay.textContent = currentThreshold.toString();
    };

    const input = body.querySelector('#threshold-input') as HTMLInputElement;
    input.onchange = () => {
        currentThreshold = parseInt(input.value, 10) || 50;
    };

    // Footer buttons
    const footer = document.createElement('div');

    const saveBtn = document.createElement('button');
    saveBtn.className = 'btn btn-primary btn-small';
    saveBtn.textContent = '保存';
    saveBtn.onclick = () => {
        // Save to state
        const rule = createStoppingRule(currentThreshold);
        state.setMlState({
            ...state.mlState,
            stoppingRule: rule
        });

        // Save to persistent storage (mock for now, should implement in storage.ts)

        renderMlStats(); // Update UI
        hideModal();
    };

    const cancelBtn = document.createElement('button');
    cancelBtn.className = 'btn btn-outline btn-small';
    cancelBtn.textContent = 'キャンセル';
    cancelBtn.onclick = () => hideModal();

    footer.appendChild(cancelBtn);
    footer.appendChild(saveBtn);

    showModal({
        title: '停止基準の設定',
        body: body,
        footer: footer
    });
}

export function showStoppingReachedDialog(onContinue: (addCount: number) => void, onFinish: () => void) {
    const body = document.createElement('div');
    body.innerHTML = `
        <div style="text-align: center; margin-bottom: 16px;">
            <p style="font-size: 16px; font-weight: bold; margin-bottom: 8px;">停止基準に到達しました</p>
            <p style="color: #666;">連続して relevant な文献が見つかりませんでした。</p>
        </div>
        
        <div class="list-item-btn" id="action-more">
            <span class="list-item-icon">📄</span>
            <div class="list-item-content">
                <span class="list-item-primary">20件追加でレビュー</span>
                <span class="list-item-secondary">閾値を+20して続行します</span>
            </div>
        </div>

        <div class="list-item-btn" id="action-finish">
            <span class="list-item-icon">📥</span>
            <div class="list-item-content">
                <span class="list-item-primary">終了してエクスポート</span>
                <span class="list-item-secondary">現在の状態で終了します</span>
            </div>
        </div>
    `;

    // Bind actions
    body.querySelector('#action-more')!.addEventListener('click', () => {
        onContinue(20);
        hideModal();
    });

    body.querySelector('#action-finish')!.addEventListener('click', () => {
        onFinish();
        hideModal();
    });

    const footer = document.createElement('div');
    const closeBtn = document.createElement('button');
    closeBtn.className = 'btn btn-outline btn-small';
    closeBtn.textContent = '閉じる (何もしない)';
    closeBtn.onclick = () => hideModal();
    footer.appendChild(closeBtn);

    showModal({
        title: '停止推奨',
        body: body,
        footer: footer
    });
}
